appenders:
  console:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)})} {h({f}:{L})} {h({l})} {h(- {m})}\n"
    filters:
      - kind: threshold
        level: trace

root: 
  level: trace
  appenders:
  - console 

loggers:
  mbase:
    level: trace
    appenders:
      - console
